const TOTAL_USERS = new Set();
const CURRENT_USER = new Set();
const TOTAL_ACTIVE_ROOMS = {};
const DISCONNECT_USER_INFO = {};

export { TOTAL_ACTIVE_ROOMS, TOTAL_USERS, CURRENT_USER, DISCONNECT_USER_INFO };
